apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qapps.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qapps
    # singular name to be used as an alias on the CLI and for display
    singular: qapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QApp
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - qapp
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # 标准定义
            spec:
              type: object
              required:
                - oauth
                - tenant
              properties:

                # 应用名称 
                text: 
                  type: string
              
                # 账号主体，默认使用租户级配置，参考 [Principal](Principal)  
                principal:
                  type: string
                  enum:
                    - openid
                    - usercode

                # 定义需要哪些oauth的scope
                oauth:
                  type: object
                  required:
                    - scopes
                  properties:
                    # OAuth scopes 
                    scopes:
                      type: array
                      description: OAuth scopes used
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name: 
                            type: string
                            description: OAuth scope name
                          grant_types:
                            type: object 
                            properties: 
                              client_credentials: 
                                type: string
                                pattern: '^(required|optional)$'
                              authorization_code:
                                type: string
                                pattern: '^(required|optional)$'
                              implicit:
                                type: string
                                pattern: '^(required|optional)$'
                              password:
                                type: string
                                pattern: '^(required|optional)$'
                # 定义产品化程度
                product:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    # 产品代码，仅产品化需要
                    name: 
                      type: string
                    version:
                      type: object
                      properties:
                        # commit-id，用于系统判断产品升级等
                        name: 
                          type: string 
                        # 人可读的版本号，如 "20210403"
                        text: 
                          type: string 
                        # 打包时间戳
                        timestamp: 
                          type: integer
                    market:
                      type: object
                      properties:
                        # 应用市场代码
                        name: 
                          type: string 
                # 多租信息
                tenant:
                  type: object
                  required:
                    - multitenancy
                  properties:
                    # 租户编码
                    name: 
                      type: string
                    # 是否支持多租。为true时，租户必须为 "localhost"
                    multitenancy: 
                      type: boolean
            # 状态定义
            status:
              type: object
              properties:
                clientId:
                  type: string
                clientSecret:
                  type: string
      subresources:
        # status enables the status subresource.
        status: {}  