apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qcharts.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qcharts
    # singular name to be used as an alias on the CLI and for display
    singular: qchart
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QChart
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    #   - qcht
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              spec:
              type: object
              required:
                - designer
                - content
              properties:
              
                # 所属应用(QApp)
                app:
                  type: object
                  properties:
                    # 所属应用的 QApp 的 metadata.name
                    name:
                      type: string

                # 设计器信息
                designer:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    # 设计器名称，如 ChartDesigner
                    name:
                      type: string
                    # 设计器版本，影响保存出来的文件格式版本
                    version:
                      type: string
                    # 额外设计器相关属性
                    attributes:
                      type: object
                        
                content:
                  type: object
                  properties:
                    kind: 
                      type: string
                      enum:
                        - Chart
                    name: 
                      type: string  # 机读标识
                    text: 
                      type: string  # 标题
                    description: 
                      type: string

                    # 《视图》配置
                    view: 
                      type: object
                      properties:
                        name: 
                          type: string
                        text: 
                          type: string
                        renders:
                          type: array
                          items:
                            type: object
                            properties:
                              # 控件ID（字段名），Content 内唯一
                              name: 
                                type: string 
                              # 控件类型
                              kind: 
                                type: string
                                enum:
                                  # 常规控件
                                  - Title       # 标题控件
                                  - HTML        # 自定义HTML内容 
                                  # 统计图
                                  - LineChart   # 折线图
                                  - BarChart    # 柱状图
                                  - PieChart    # 饼图
                                  - Gauge       # 仪表盘
                                  - KPI         # KPI
                                  - DataTable   # 数据表 
                                  - PivotTable  # 透视表 
                              # 标题
                              text:
                                type: string
                              # 描述
                              description: 
                                type: string
                              # 控件内容，仅用于HTML控件 
                              body: 
                                type: string
                              # 外部链接
                              uri:
                                type: string
                              # 位置，（x, y, w, h）
                              position:
                                type: object
                                properties:
                                  x:
                                    type: integer
                                  y:
                                    type: integer
                                  w:
                                    type: integer
                                  h:
                                    type: integer
                              # ECharts 高级设置
                              echarts:
                                type: object
                                properties:
                                  # 可额外属性定义，JSON语法，覆盖默认配置 
                                  options:
                                    type: string 
                              # 分组。使用方式：
                              # Line、Bar、Pie、Guage、KPI: 仅使用group[0]作为x轴（invert后为y轴）
                              # DataTable：作为表列（不支持invert）
                              # PivotTable：度量值作为表列（invert后为表行）
                              groups:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    # 维度名（用于计算）
                                    dimension:
                                      type: string
                                    # 维度名（用于显示）
                                    textDimension:
                                      type: string
                                    # 行列反转
                                    invert:
                                      type: boolean
                                    # 格式化串，用于格式化时间
                                    format:
                                      type: string
                                    # 最小值
                                    min:
                                      type: string
                                    # 最大值
                                    max: 
                                      type: string
                                    # 总显示量，超出显示量时显示为"其他"
                                    total:
                                      type: string
                              # 度量值
                              # Line、Bar: 可多值
                              # KPI、Guage、Pie: 单值
                              # DataTable: 作为表列
                              # PivotTable：作为表内容
                              values: 
                                type: array
                                items:
                                  type: object
                                  properties:
                                    # 度量名（用于计算）
                                    metric:
                                      type: string 
                                    # 聚合方式，仅用于 Guage
                                    aggregation:
                                      type: string
                                      enum:
                                        - count
                                        - sum
                                        - average
                                    # 格式化串，用于格式化货币等
                                    format:
                                      type: string
                                    # 定义颜色、线型等
                                    styles:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          name: 
                                            type: string 
                                            enum:
                                              - color
                                              - weight
                                          # 用于Line、Bar、Guage等，一个度量一种颜色的
                                          value:
                                            type: string
                                          # 用于Pie，多值循环使用
                                          values:
                                            type: array
                                            items:
                                              type: string
                                              
                              # 轴线
                              axes: 
                                type: array
                                items:
                                  type: object
                                  properties:
                                    # 轴线位置
                                    position:
                                      type: string
                                      enum:
                                        - top
                                        - left
                                        - right
                                        - bottom 
                                    # 轴线标题 
                                    text:
                                      type: string
                              # 图例
                              legend:
                                type: object
                                properties:
                                  # 是否显示
                                  show:
                                    type: boolean 
                                  dimension:
                                    type: string 
                              # 数据
                              data:
                                type: object
                                properties:
                                  # 数据源
                                  source:
                                    type: object
                                    properties:
                                      # 数据源类型
                                      kind:
                                        type: string
                                        enum:
                                          - hub   # 从数据源选择，包括关系型数据库、ElasticSearch、Prometheus、REST 等
                                          - bus   # 从数据网关选择
                                      # 数据源名称（来自hub）或者服务名（来自bus）
                                      name: 
                                        type: string
                                      text:
                                        type: string
                                  # 查询语句
                                  query:
                                    type: object
                                    properties:
                                      kind: 
                                        type: string
                                        enum:
                                          - sql
                                          - elastic_search
                                          - prometheus
                                          - graphql
                                      statement:
                                        type: string
                                      
                                  # 《维度》列表
                                  dimensions:
                                    type: array
                                    items:
                                      type: object 
                                      properties:
                                        name: 
                                          type: string 
                                        text: 
                                          type: string 
                                        field:
                                          type: string
                                  # 《度量》列表
                                  metrics:
                                    type: array
                                    items:
                                      type: object 
                                      properties:
                                        name: 
                                          type: string 
                                        text: 
                                          type: string 
                                        # 对于SQL，直接对应字段名；对于GraphQL和REST，可使用路径指定字段，比如 data[0].totalCount
                                        field:
                                          type: string
