apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qdatasources.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qdatasources
    # singular name to be used as an alias on the CLI and for display
    singular: qdatasource
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QDataSource
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - qapp
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # 标准定义
            spec:
              type: object
              required:
                - name
                - text
                - url
                - kind
                - schema
              properties:
                # 数据源标识
                name:
                  type: string
                # 数据源显示名
                text:
                  type: string
                # 数据源地址，jdbc url
                url:
                  type: string
                # 类型
                kind:
                  type: string
                  enum:
                    - mysql
                    - oracle
                    - mssql
                    - tidb
                    - postgrel
                    - hive
                    - prometheus
                    - elasticsearch
                    - http

                # 安全信息
                security:
                  type: object
                  properties:
                    # 管理模式
                    kind:
                      type: string
                      enum:
                        - managed    # 由系统托管
                        - password   # 指定用户名/口令 
                        - http       # 通过 HTTP 方式认证
                    # 托管配置
                    managed:
                      type: object
                      required:
                        - datasourceRef
                      properties:
                        # 上游数据源
                        datasourceRef:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                    # HTTP方式认证配置
                    http: 
                      type: object
                      properties:
                        # HTTP请求
                        request:    &REQUEST
                          type: object
                          properties:
                            # 认证地址
                            uri:
                              type: string
                            # HTTP方法
                            method: 
                              type: string
                            # HTTP头
                            headers:
                              type: array
                              items:
                                type: object
                                properties:
                                  # HTTP头名称
                                  name:
                                    type: string
                                  # HTTP头取值
                                  value:
                                    type: string
                            # HTTP请求体
                            body:
                              type: string
                            # HTTP参数，用于 QueryString 或 Form
                            parameters:
                              type: array
                              items:
                                type: object
                                required:
                                  - name
                                properties:
                                  # 参数名
                                  name:
                                    type: string
                                  # 人读描述
                                  text:
                                    type: string
                                  # 参数值，等号开头为表达式
                                  value:
                                    type: string

                        # HTTP响应
                        response:   &RESPONSE
                          type: object
                          properties:
                            # 变量解析
                            variables:  &VARIABLES
                              type: array
                              items:
                                type: object
                                properties:
                                  # 变量名，如 "access_token"
                                  name:
                                    type: string
                                  # 变量解析路径，如 "result.access_token"
                                  path:
                                    type: string

                    # 账号列表
                    # 每个账号生成一个secret，生成规则：
                    # data 类型生成 qdatasource-{name}-secret-0 ...
                    # full 类型生成 qdatasource-{name}-secret-full-0 ...
                    # readonly 类型生成 qdatasource-{name}-secret-readonly-0 ... 
                    # secret 字段名：
                    #   url：数据库连接字符串
                    #   username: 用户名
                    #   password: 密码
                    #   protocol: 协议部分，比如 "jdbc:mariadb://" 
                    #   host：主机名
                    #   port：端口号
                    #   database: 数据库表名
                    #   query: 查询字符串
                    users:
                      type: array
                      items:
                        type: object
                        required:
                          - username
                          - permission
                        properties:
                          # 数据源用户名
                          username:
                            type: string
                          # 数据源密码，仅password模式需要
                          passwordFrom:
                            type: object
                            properties:
                              # 通过 secret 引用
                              secretRef:
                                type: object
                                properties:
                                  # secret名
                                  name: 
                                    type: string
                                  # 密码字段key
                                  key:
                                    type: string
                          # 权限
                          permission:
                            type: string
                            enum:
                              - full      # 完整权限，DML & DDL
                              - data      # 数据权限，仅DML
                              - readonly  # 只读 


                # 数据库信息
                schema:
                  type: object
                  properties:
                    # 数据库 schema 名称
                    name: 
                      type: string
                    # 数据类型列表
                    types:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                          - source
                        properties:
                          # 数据类型名（机读）
                          name:
                            type: string
                          # 显示名
                          text:
                            type: string
                          # 数据来源信息
                          source:
                            type: object
                            properties:
                              kind:
                                type: string
                                enum:
                                  - table
                                  - view
                                  - script  # 根据SQL生成
                                  - http    # 根据HTTP请求生成
                              # 数据表模式
                              table:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  # 是否只读
                                  readonly:
                                    type: boolean
                              # 视图模式
                              view:
                                type: object
                                properties:
                                  name:
                                    type: string
                              # 脚本模式
                              script:
                                type: object
                                properties:
                                  # 根据SQL生成
                                  sql:
                                    type: string
                              # HTTP模式
                              http:
                                type: object
                                properties:
                                  # HTTP请求
                                  request: *REQUEST
                                  # HTTP响应
                                  response: *RESPONSE
                                  paginition:
                                    type: object
                                    properties:
                                      kind:
                                        type: string
                                        enum:
                                          - none    # 不支持分页
                                          - page    # 页码模式
                                          - cursor  # 游标模式 

                                  # 操作列表定义，用于GraphQL映射。可选。
                                  operations:
                                    type: array
                                    items:
                                      type: object
                                      properites:
                                        # 操作名
                                        name: 
                                          type: string
                                        # 操作类型
                                        kind:
                                          type: string
                                          enum:
                                            - query
                                            - mutation
                                        # 该操作的HTTP请求重载
                                        override:
                                          type: object
                                          properties:
                                            # HTTP方法
                                            method:
                                              type: string
                                        # 变量列表
                                        # 比如，对于请求地址：https://example.com/api/{path}，可定义多个操作 => 变量
                                        #   操作1: path = "users"
                                        #   操作2: path = "user/{id}"
                                        variables: *VARIABLES
                                        


                          # 字段映射
                          fields:
                            type: array
                            items:
                              type: object
                              required:
                                - name
                                - source
                              properties:
                                # 接口字段名称
                                name:
                                  type: string
                                # 字段备注
                                text:
                                  type: string
                                # 数据来源信息
                                source:
                                  type: object
                                  properties:
                                    # 数据库字段名
                                    name:
                                      type: string
                                    # 数据库字段类型
                                    dataType:
                                      type: string
                                # 是否必填
                                notNull:
                                  type: boolean
                                # 接口数据类型
                                # ID、Int、String、Account、Dept、Timestamp、UnixTimestamp、Disabled、Base64、Tenant
                                dataType:
                                  type: string
                                # 多租支持
                                tenant:
                                  type: object
                                  properties:
                                    # 租户标识字段名，如不定义，则当前类型不支持多租
                                    field:
                                      type: string
                                    # 租户数据类型名称。如不定义，则直接使用底座租户标识过滤，否则根据租户标识查询此类型Tenant字段，使用租户表ID过滤
                                    tenantType:
                                      type: string

                # 数据脚本任务，仅支持有写权限的数据库，要求 DDL 权限
                tasks:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - kind
                    properties:
                      # 任务名称，机读，记录在当前数据库 QDataSource_History 表中，避免重复执行
                      name:
                        type: string
                      # 脚本类型
                      # 执行逻辑：
                      # 1. 数据库不存在 & managed模式下：仅执行 init 脚本，并创建 QDataSource_History 表
                      # 2. 数据库存在 & QDataSource_History 表存在，严格按 tasks 数组顺序执行 update 脚本，失败则终止后续执行
                      # 3. 数据库存在 & QDataSource_History 表不存在，不执行任何脚本
                      kind:
                        type: string
                        enum: 
                          - init      # 初始化脚本
                          - update    # 增量脚本
                      # 脚本内容
                      script:
                        type: string
                      # 外部引用脚本
                      scriptFrom:
                        type: object
                        properties:
                          configMapRef:
                            type: object
                            required:
                              - name
                            properties:
                              # configmap 名称
                              name:
                                type: string
                              # configmap key
                              key:
                                type: string

                # QDataSource多租信息
                tenant:
                  type: object
                  required:
                    - multitenancy
                  properties:
                    # 租户编码
                    name: 
                      type: string
                    # 是否支持多租。为true时，租户必须为 "localhost"
                    multitenancy: 
                      type: boolean
