apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qforms.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qforms
    # singular name to be used as an alias on the CLI and for display
    singular: qform
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QForm
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - qfrm
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - designer
                - content
              properties:

                # 所属应用(QApp)
                app:
                  type: object
                  properties:
                    # 所属应用的 QApp 的 metadata.name
                    name:
                      type: string
                    # 新建租户时是否需要自动激活
                    autoActivate:
                      type: boolean
                    # 内容变化时，已激活的租户中本应用是否自动升级
                    autoUpgrade:
                      type: boolean

                # 设计器信息
                designer:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    # 设计器名称，如 SurveyDesigner、InfoPath
                    name:
                      type: string
                    # 设计器版本，影响保存出来的文件格式版本
                    version:
                      type: string
                    # 额外设计器相关属性
                    attributes:
                      type: object
                        
                content:
                  type: object
                  properties:
                    kind: 
                      type: string
                      enum:
                        - Form
                    name: 
                      type: string  # 机读标识
                    text: 
                      type: string  # 标题
                    description: 
                      type: string

                    # 多视图设置，尚无需支持。参考：https://github.com/infoplus/docs/wiki/ViewPage
                    views: 
                      type: array
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          # 视图标识，QForm 内唯一
                          name: 
                            type: string
                          # 视图显示名
                          text: 
                            type: string
                          # 控件标签通用属性
                          label: &LABEL
                            type: object
                            properties:
                              # 可见性，支持表达式
                              visible:
                                type: string
                              # 标签停靠位置
                              dock:
                                type: string
                                enum:
                                  - auto
                                  - left
                                  - top
                              # 宽度
                              width:
                                type: integer
                              # 内容
                              text:
                                type: string
                          
                          # 控件列表
                          renders:
                            type: array
                            items:
                              type: object
                              properties:
                                # 控件ID（字段名），Content 内唯一
                                name: 
                                  type: string
                                # 控件分类：数据控件、布局控件、显示控件
                                category: 
                                  type: string
                                  enum:
                                    - Boundable
                                    - Layoutable
                                    - Displayable
                                # 控件类型
                                kind: 
                                  type: string 
                                  enum:
                                    # 显示控件
                                    - Title           # 标题控件
                                    - HorizontalRule  # 分割线
                                    - PageBreak       # 分页符
                                    - SectionBreak    # 分节符
                                    
                                    # 布局控件
                                    - Section         # 节
                                    - Table           # 表
                                    - RepeatSection   # 重复节
                                    - RepeatTable     # 重复表

                                    # 业务控件（同数据控件，需绑定字段）
                                    - User            # 当前用户
                                    - Dept            # 当前用户所属部门

                                    # 数据控件
                                    - Edit        # 文本框，单行文本 
                                    - TextArea    # 大文本框，多行文本
                                    - RichText    # 富文本框，输入富文本
                                    - Remark      # 备注文本框，可输入多行文本，但只显示一个图标表示有无输入
                                    - Date        # 日期，以yyyy-mm-dd的格式输入日期
                                    - Time        # 时间，以mm:ss的格式输入时间
                                    - Check       # 复选框，复选项
                                    - Switch      # 切换开关，切换状态开关
                                    - CheckList   # 复选框，以代码表作为复选项
                                    - Option      # 单选框，单选项
                                    - OptionList  # 单选框，以代码表作为单选项
                                    - Select      # 下拉框，下拉输入
                                    - Suggester   # 提示输入框，带有智能提示的输入文本框
                                    - Label       # 标签，标签显示内容，不可输入
                                    - Hidden      # 隐藏字段，隐藏内容，不显示
                                    - Anchor      # 链接，超链接，可以多种方式打开
                                    - File        # 文件，文件上传
                                    - Image       # 图片显示，显示图片
                                    - Picture     # 图片上传，图片上传
                                    - Help        # 帮助，显示一个帮助图标，点上去出帮助提示
                                    - Button      # 按钮，显示一个按钮，点击后会触发后台fieldChange
                                    - LinkButton  # 链接按钮，显示一个链接，点击后会触发后台fieldChange
                                    - CheckButton # check按钮，显示一个按钮，有选中和不选中两种状态
                                    - Thing       # 物品，输入物品
                                    - IFrame      # iframe，用于设计第三方控件
                                    - Map         # 地图，用于显示位置或者让用户选取位置
                                    - Seal        # 印章，数字印章的选取和显示
                                    - Signature   # 签名，对指定表单数据进行签名和验证
                                # 是否必填，仅 `数据控件` 支持
                                required: 
                                  type: boolean 
                                # 对应数据字段，仅 `数据控件` 支持
                                field: 
                                  type: string 
                                # 格式：File/Picture控件用于限制文件类型
                                format:
                                  type: string
                                # 控件无内容时的提示信息
                                placeholder:
                                  type: string 
                                # 最小长度
                                minLength:
                                  type: integer
                                # 最大长度
                                maxLength:
                                  type: integer
                                # 最大行数：用于TextArea
                                lines:
                                  type: integer

                                # 标签选项
                                label: *LABEL

                                # 响应时布局
                                layout:
                                  type: object
                                  properties:
                                    # 所占列数，默认全宽（PC: 24）
                                    columns: 
                                      type: integer

                                # 控件提示信息
                                tooltip:
                                  type: object
                                  properties:
                                    # 内容
                                    text:
                                      type: string

                                # 验证
                                validations:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 验证的正则表达式（或 = 开头表示 boolean 表达式）
                                      value:
                                        type: string
                                      # 提示信息
                                      text: 
                                        type: string
                                # 样式（css）
                                styles:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 如：width: 200px;
                                      value:
                                        type: string

                                # 数据源，用于 Select 等
                                source:
                                  type: object
                                  properites:
                                    kind: 
                                      type: string
                                      enum:
                                        # 内部代码表
                                        - internal
                                        # 数据网关
                                        - external
                                        # 常量（后面items）
                                        - constant
                                    # 动态代码表
                                    code:
                                      type: string
                                    # 常量代码表项
                                    items:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          # 值ID
                                          name:
                                            type: string
                                          # 显示值
                                          text:
                                            type: string

                                # 图标
                                icons:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 位置
                                      dock:
                                        type: string
                                        enum:
                                          - left
                                          - right
                                      # 图标值
                                      value:
                                        type: string

                                # 子控件列表，仅 `布局控件` 支持
                                renders:
                                  type: array
                                  items:
                                    type: object
                                    properties: 
                                      nameRef: 
                                        type: string 

                # 数据定义
                data:
                  type: object
                  properties:
                    # 数据类型机读标识
                    name:
                      type: string
                    # 显示名
                    text:
                      type: string
                    # 所需字段
                    fields:
                      type: array
                      items:
                        type: object
                        properties:
                          # 字段名
                          name: 
                            type: string
                          # 显示名
                          text:
                            type: string 
                          # 数据类型
                          type:
                            type: string
                          # 数据层次，用于重复表
                          group:
                            type: string
                            
                          # 初始值
                          initialize:
                            type: object
                            properties:
                              # 初始值
                              value: 
                                type: string
                              # 初始值条件
                              condition:
                                type: string
                                enum:
                                  - Blank
                                  - Always
                              readOnly:
                                type: boolean

                # 代码表定义
                codes:
                  type: array
                  items:
                    type: object
                    properites:
                      # 数据类型名
                      name:
                        type: string
                      # 数据操作（GraphQL查询）
                      operation:
                        type: object
                        properites:
                          kind:
                            type: string
                            enum:
                              - query
                          name:
                            type: string
                          # 该《数据操作》所需字段
                          fields:
                            type: array
                            items: 
                              type: object 
                              properites:
                                # 使用方式暗示
                                kind:
                                  type: string
                                  enum:
                                    - text
                                    - value
                                    - icon
                                    - tooltip
                                # 字段名
                                name:
                                  type: string
                                # 字段显示名
                                text:
                                  type: string
                                # 字段类型
                                type:
                                  type: string 
                          # 该《数据操作》所需Filter
                          # 参考：https://github.com/infoplus/canvas-docs/wiki/Filter
                          filters:
                            type: array
                            items: 
                              type: object 
                            required:
                              - field
                            # anyOf:
                            #  - required:
                            #    - value
                            #    - values
                            #    - experssion
                            properties:
                              field:
                                type: string
                              match:
                                type: string
                                enum:
                                  - eq 
                                  - neq
                                  - in
                                  - nin
                                  - gt
                                  - gte
                                  - lt
                                  - lte
                                  - like
                              value:
                                x-kubernetes-int-or-string: true
                              values:
                                type: array
                                items:
                                  x-kubernetes-int-or-string: true
                              experssion:
                                type: string
                          
                          # 该《数据操作》所需参数
                          arguments:
                            type: array
                            items:
                              type: object 
                              required:
                                - name
                                - value
                              properties:
                                # 字段数据类型，仅支持简单类型
                                type:
                                  type: string
                                # 参数名
                                name:
                                  type: string
                                value:
                                  x-kubernetes-int-or-string: true

                
