apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qlicenses.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qlicenses
    # singular name to be used as an alias on the CLI and for display
    singular: qlicense
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QLicense
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - qlic
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - text
                - license
              properties:
                # 描述
                text:
                  type: string

                # 请求授权的范围，比如服务、菜单等，仅用于描述/人读，不影响实际授权
                scopes:
                  type: array
                  items: 
                    type: object 
                    properties:
                      # 授权对象名，如服务名、站点地图名等
                      name: 
                        type: string
                      
                      # 请求授权的对象类型
                      kind:
                        type: string
                        enum:
                          - service
                          - sitemap

                      # 功能点
                      features: 
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            dataType:
                              type: string
                            # 授权值，注意此处类型均为 string，实际类型应以 dataType 为准。
                            value:
                              type: string 

                      # 超时时间，Unix时间戳
                      expire:
                        type: integer


                # 授权信息，JWT格式
                license:
                  type: string 

                # 授权链信息
                chain:
                  type: object
                  properties:
                    # 授权颁发者信息，批量授权名称
                    issuer:
                      type: string

                # 多租信息
                tenant:
                  type: object
                  required:
                    - multitenancy
                  properties:
                    # 租户编码
                    name: 
                      type: string
                    # 是否支持多租。为true时，租户必须为 "localhost"
                    multitenancy: 
                      type: boolean


