apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qservices.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - tenant
              properties:
                # 多租信息
                tenant:
                  type: object
                  required:
                    - multitenancy
                  properties:
                    # 租户编码
                    name: 
                      type: string
                    # 是否支持多租。为true时，租户必须为 "localhost"
                    multitenancy: 
                      type: boolean
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qservices
    # singular name to be used as an alias on the CLI and for display
    singular: qservice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QService
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - qsvc