apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: qworkshops.ketanyun.cn
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ketanyun.cn
    # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: qworkshops
    # singular name to be used as an alias on the CLI and for display
    singular: qworkshop
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QWorkshop
    # shortNames allow shorter string to match your resource on the CLI
    #shortNames:
    #  - qrole
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                # 车间编码
                name:
                  type: string
                # 车间名称
                text:
                  type: string

                # 车间部件
                parts:
                  type: array
                  items: 
                    type: object
                    properties:
                      # 组件编码，UUID，租户内唯一
                      name:
                        type: string
                      # 显示名
                      text:
                        type: string
                      # 描述
                      description: 
                        type: string
                      # 标签
                      tags: 
                        type: string
                      # 类型，包含于 AssembleConfiguration.partKinds
                      kind: 
                        type: string
                      # OAuth应用，引用自resources节
                      client:
                        type: string

                      # 环境列表
                      environments:
                        type: array
                        items:
                          type: object
                          properties:
                            kind: 
                              type: string
                              # 环境类型
                              enum:
                                - production
                                - development
                              # 对应版本
                              version:
                                type: string

                      # 版本列表
                      versions:
                        type: array
                        items: 
                          type: object
                          properties:
                          
                            # 当前版本机读标识
                            name:
                              type: string

                            # 根部件项
                            item: &PART_ITEM
                              type: object
                              properties:
                                # 部件项标识
                                name:
                                  type: string
                                # 部件项名称
                                text:
                                  type: string
                                # 父项
                                parent:
                                  type: string
                                # 类型
                                kind:
                                  type: string
                                # 插槽列表
                                slots:
                                  type: array
                                  items: &PART_SLOT
                                    type: object  
                                    properties:
                                      # 插槽标识
                                      name:
                                        type: string
                                      # 插槽文字
                                      text:
                                        type: string
                                      # 插槽类型
                                      kind:
                                        type: string
                                        enum:
                                          - link
                                      # 引用部件
                                      partRef:
                                        type: object
                                        properties:
                                          # 部件名称
                                          name:
                                            type: string
                                          # 插槽取值，因插槽类型而异；支持变量，格式 ${VAR}，变量内容需根据实际环境从网关按 label=assemble 读取
                                          value:
                                            type: string
                                            
                                # 依赖列表
                                dependencies:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      # 依赖标识
                                      name:
                                        type: string
                                      # 类型，支持 UserFilter 和 TypeFilter
                                      kind:
                                        type: string
                                      # 依赖名称
                                      text:
                                        type: string
                                      # 值，因类型而异
                                      value:
                                        type: string

                            # 部件项列表
                            items:
                              type: array
                              items: *PART_ITEM

                      # 布局
                      layout:
                        type: object
                        properties:
                          # 横坐标
                          x: 
                            type: string
                          # 纵坐标
                          y: 
                            type: string
                          # 是否展开
                          expand:
                            type: boolean

                # 车间可使用的资源列表
                resources:
                  type: object
                  properties:

                    # OAuth应用列表
                    clients:
                      type: array
                      items:
                        type: object
                        properties:
                          # 应用ID
                          name:
                            type: string
                          # 应用名称
                          text:
                            type: string
                          # 授权范围
                          scopes:
                            type: array
                            description: OAuth scopes used
                            items:
                              type: object
                              required:
                                - name
                              properties:
                                name: 
                                  type: string
                                  description: OAuth scope name
                                grant_types:
                                  type: object 
                                  properties: 
                                    authorization_code: &GRANT
                                      type: string
                                      enum:
                                        - required
                                        - optional 
                                    client_credentials: *GRANT
                                    implicit: *GRANT
                                    password: *GRANT


                    # 人员身份列表
                    users:
                      type: array
                      items:
                        type: object
                        properties:
                          # 显示内容
                          text:
                            type: string
                          # 用户筛选器
                          userFilter:
                            type: string

                    # 外部类型依赖
                    types:
                      type: array
                      items:
                        type: object
                        properties:
                          # 显示内容
                          text:
                            type: string
                          # 类型筛选器
                          typeFilter:
                            type: string

                      

                      



                      




                  